<a href="https://colab.research.google.com/github/vhcontre/data-analytics-con-python/blob/main/data_analytics_con_python_clase_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# V√≠ctor H

Hola! Soy Victor, y me encanta aprender Data Analytics con Python. Aqu√≠ van algunas cosas sobre m√≠:

**Fortalezas:**
- Trabajo en proyectos de software
- Me gusta aprender cosas nuevas
- Disfruto organizar y planificar

*Recuerden siempre*: la pr√°ctica hace al maestro.

Documentaci√≥n oficial de Python: [Python Docs](https://docs.python.org/3/)


> ‚ÄúEl conocimiento es poder, pero la sabidur√≠a es aplicarlo.‚Äù

# ¬©Ô∏è Clase 6

## Actividad 1: An√°lisis de Supervivencia (Obligatoria)

**Consigna:**

1. Filtrar pasajeros sobrevivientes.
2. Seleccionar columnas: `'sex'`, `'age'`, `'fare'`.
3. Crear una nueva columna seg√∫n la clase del pasajero.

In [ ]:
import seaborn as sns
import pandas as pd

# Cargar dataset Titanic desde Seaborn
df_titanic = sns.load_dataset('titanic')

# Ver las primeras filas
print(df_titanic.head())
df_titanic.to_csv("titanic.csv", index=False)

In [ ]:
import pandas as pd
import seaborn as sns
from google.colab import files

# 1Ô∏è‚É£ Subir archivo Titanic desde la PC
# print("üëâ Selecciona el archivo titanic.csv desde tu PC")
# uploaded = files.upload()
# nombre_archivo = list(uploaded.keys())[0]

# 2Ô∏è‚É£ Cargo el dataset Titanic
# df_titanic = pd.read_csv(nombre_archivo)
df_titanic = sns.load_dataset('titanic')

print("\n‚úÖ Dataset Titanic cargado con √©xito")
print("Primeras filas del dataset original:")
print(df_titanic.head())

# 3Ô∏è‚É£ Filtro solo a los pasajeros que sobrevivieron
df_survivors = df_titanic[df_titanic['survived'] == 1]

print("\n‚úÖ Cantidad de sobrevivientes:", df_survivors.shape[0])

# 4Ô∏è‚É£ Selecciono columnas relevantes
df_selected = df_survivors[['sex', 'age', 'fare', 'class']]

print("\n‚úÖ Columnas seleccionadas (sex, age, fare, class):")
print(df_selected.head())

# 5Ô∏è‚É£ Creo nueva columna con la clase categorizada
df_selected['clase_categoria'] = df_selected['class'].map({
    'First': 'Alta',
    'Second': 'Media',
    'Third': 'Baja'
})

print("\n‚úÖ Nueva columna 'clase_categoria' creada:")
print(df_selected.head())

# 6Ô∏è‚É£ Resumen final (tabla con primeros registros)
print("\nüìä Dataset final preparado (primeros 10 registros):")
print(df_selected.head(10))

# 7Ô∏è‚É£ Guardar dataset final
df_selected.to_excel("titanic_supervivientes.xlsx", index=False)
print("\nüíæ Dataset final guardado como 'titanic_supervivientes.xlsx'")

### Ejemplo de salida final (tabla con primeros registros)

| sex    | age  | fare   | class  | clase\_categoria |
| ------ | ---- | ------ | ------ | ---------------- |
| female | 38.0 | 71.283 | First  | Alta             |
| female | 26.0 | 7.925  | Third  | Baja             |
| female | 35.0 | 53.100 | First  | Alta             |
| female | 27.0 | 11.133 | Third  | Baja             |
| male   | 54.0 | 51.862 | First  | Alta             |
| male   | 4.0  | 16.700 | Third  | Baja             |
| female | 58.0 | 26.550 | First  | Alta             |
| male   | 34.0 | 13.000 | Second | Media            |
| female | 2.0  | 21.075 | Third  | Baja             |
| female | 31.0 | 18.000 | Third  | Baja             |

## Actividad 2 Manipulaci√≥n de Datos

**Consigna:**

1. Obtener los nombres de las columnas.
2. Eliminar la columna `'deck'` (contiene nulos).
3. Reindexar el DataFrame.

In [6]:
import pandas as pd
import seaborn as sns

# Cargar dataset Titanic usando Seaborn
df = sns.load_dataset('titanic')
print("Primeras filas del dataset cargado con Seaborn:")
display(df.head())

# Obtener nombres de las columnas
columnas = df.columns.tolist()
print("\nNombres de las columnas:")
print(columnas)

# Eliminar columna 'deck'
if 'deck' in df.columns:
    df = df.drop(columns=['deck'])
    print("\nColumna 'deck' eliminada correctamente.")
else:
    print("\nLa columna 'deck' no existe en el dataset.")

# Reindexar DataFrame
df = df.reset_index(drop=True)
print("\nDataFrame reindexado. Primeras filas del DataFrame modificado:")
display(df.head())

# Resumen final en tabla
resumen_final = pd.DataFrame({
    "N√∫mero de filas": [df.shape[0]],
    "N√∫mero de columnas": [df.shape[1]],
    "Columnas restantes": [df.columns.tolist()]
})
print("\nResumen final del DataFrame:")
display(resumen_final)

Primeras filas del dataset cargado con Seaborn:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Nombres de las columnas:
['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

Columna 'deck' eliminada correctamente.

DataFrame reindexado. Primeras filas del DataFrame modificado:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

Resumen final del DataFrame:

,N√∫mero de filas,N√∫mero de columnas,Columnas restantes
0,891,14,"[survived, pclass, sex, age, sibsp, parch, far..."